### PR TITLE
rewritten code

### PR DESCRIPTION
**Pull request by mattis1231231**

### CODE REVIEW

**Comment by Smile249** [comment]
Some of this won't work I am pretty sure. DiscordJS is quite annoying when making code "cleaner". I can remove some stuff that is left unused but I don't see any use in rewriting it to that level, its a private little project after all.

**Comment by mattis1231231** [comment]
maybe you could consider making an app. because the idea itself is not bad, especially because I have already made it myself.




this was one of the first versions.

**Comment by Smile249** [comment]
I know like nothing about app development and I'm an iPhone user so I'm gonna have to use swift (which i don't know AT ALL)

**Comment by mattis1231231** [comment]
> I know like nothing about app development and I'm an iPhone user so I'm gonna have to use swift (which i don't know AT ALL)

you could use react native

**Pull request closed without merging**
